<a href="https://colab.research.google.com/github/kashishthorat812-bit/NumPy_Project/blob/main/TASK13_Q8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# create a 4*4 matrix of random integer between 1,100
A=np.random.randint(1,101,(4,4))
print("Matrix :")
print(A)

print("\n<<----Properties---->>")
# print the shape of matrix using shape method
print("Shape od matrix = ",np.shape(A))

# print the dimension of matrix using (ndim)
print("Dimension of matrix = ",np.ndim(A))

# print the total numbers of element (size) using Size method
print("Size of matrix = ",np.size(A))

# print the data type of matrix using dtype method
print("Data Type of matrix = ",A.dtype)

# print maximum value using a (max)
print("Maximum value = ",np.max(A))

# print minimum value using a (mim)
print("Minimum value = ",np.min(A))

Matrix :
[[99 72 55 16]
 [77 20 58 30]
 [29 65 74 21]
 [10 84 27 46]]

<<----Properties---->>
Shape od matrix =  (4, 4)
Dimension of matrix =  2
Size of matrix =  16
Data Type of matrix =  int64
Maximum value =  99
Minimum value =  10
