<a href="https://colab.research.google.com/github/kashishthorat812-bit/NumPy_Project/blob/main/TASK13_Q5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# print Random 10 numbers between 0 and 1 using rand
print("Random 10 numbers between 0 and 1 :")
a=np.random.rand(10)
print(a)

# print Random number of matrix 3*3 using randn
a2=np.random.randn(3,3)
print("\nRandom number of matrix 3*3")
print(a2)

# print 2D Array of random integers between 10 to 50 with matrix 4*5 using randint
a3=np.random.randint(10,51,(4,5))
print("\n2D Array of random integers between 10 to 50 with matrix 4*5 :")
print(a3)

Random 10 numbers between 0 and 1 :
[0.08830208 0.1118366  0.31278358 0.06128317 0.86662221 0.62738376
 0.43545867 0.0609441  0.16138191 0.53169906]

Random number of matrix 3*3
[[-7.13374448e-01  4.43271706e-01 -2.44390909e-01]
 [ 3.60866140e-04  1.05920866e+00  7.87361318e-01]
 [ 4.23193720e-01 -1.41228379e+00  1.48313784e+00]]

2D Array of random integers between 10 to 50 with matrix 4*5 :
[[49 42 46 22 33]
 [47 37 16 25 14]
 [23 14 28 49 30]
 [41 30 18 40 37]]
