<a href="https://colab.research.google.com/github/kashishthorat812-bit/NumPy_Project/blob/main/TASK13_Q10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

try:
    n = int(input("How many numbers do you want to generate? "))

    if n <= 0:
        print("Please enter a positive number.")
    else:
        arr = np.random.randint(10, 101, n)

        print("\nGenerated Array:")
        print(arr)

        print("\n<<----Statastics---->>")
        print("Mean:", np.mean(arr))
        print("Median:", np.median(arr))
        print("Standard Deviation:", np.std(arr))
        print("Minimum:", np.min(arr))
        print("Maximum:", np.max(arr))

        if n % 2 == 0:
            arr2d = arr.reshape(2, n // 2)
            print("\nReshaped 2D Array:")
            print(arr2d)

            print("\nRow-wise Sum:")
            print(np.sum(arr2d, axis=1))
        else:
            print("\nCannot reshape into 2D array equally because number count is odd.")

except ValueError:
    print("Invalid input! Please enter an integer.")

How many numbers do you want to generate? 6

Generated Array:
[34 57 51 96 35 90]

<<----Statastics---->>
Mean: 60.5
Median: 54.0
Standard Deviation: 24.4455176532086
Minimum: 34
Maximum: 96

Reshaped 2D Array:
[[34 57 51]
 [96 35 90]]

Row-wise Sum:
[142 221]
