<a href="https://colab.research.google.com/github/kashishthorat812-bit/NumPy_Project/blob/main/TASK13_Q6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
v1=np.array([2,4,6,8])
v2=np.array([1,3,5,7])

# Addition of two vector
add=v1+v2
print("Addition :")
print(add)

# Substraction of two vector
sub=v1-v2
print("\nSubstraction :")
print(sub)

# Multiplication of two vector
mul=v1*v2
print("\nElement-wise Multiplication :")
print(mul)

mul2=np.dot(v1,v2)
print("\nDot Product :")
print(mul2)

Addition :
[ 3  7 11 15]

Substraction :
[1 1 1 1]

Element-wise Multiplication :
[ 2 12 30 56]

Dot Product :
100
