<a href="https://colab.research.google.com/github/kashishthorat812-bit/NumPy_Project/blob/main/TASK13_Q9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# create a 1D array of 20 random integers
a=np.random.randint(1,50,20)
print("1D Array :")
print(a)

# reshape the 1D array into 4*5 matrix
matrix=a.reshape(4,5)
print("\n4*5 Matrix :")
print(matrix)

# sum ,mean and standard Deviation of matrix
print("\n<<----Statistics---->>")
print("Sum of matrix = ",np.sum(matrix))
print("Mean of matrix = ",np.mean(matrix))
print("Standard deviation of matrix = ",np.std(matrix))

# maximum value in each row
print("\nMaximum value in each row :")
print(np.max(matrix,axis=1))

1D Array :
[20 25 41 27 18 49 37 29  1 28 18 49 32 40 40 42  8 42 31 45]

4*5 Matrix :
[[20 25 41 27 18]
 [49 37 29  1 28]
 [18 49 32 40 40]
 [42  8 42 31 45]]

<<----Statistics---->>
Sum of matrix =  622
Mean of matrix =  31.1
Standard deviation of matrix =  12.918591254467339

Maximum value in each row :
[41 49 49 45]
