<a href="https://colab.research.google.com/github/kashishthorat812-bit/NumPy_Project/blob/main/TASK13_Q7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# create a two 3*3 matrix
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])

# Addition of two matrix
add=A+B
print("\nAddition of two matrix :")
print(add)

# Multiplication of two matrix using ( @ )
mul=A@B
print("\nMultiplication of two matrix :")
print(mul)

# Multiplication of two matrix using (dot )
mul2=np.dot(A,B)
print("\nMultiplication of two matrix using (dot ) :")
print(mul2)

# Element-wise multiplication
mul3=A*B
print("\nElement-wise multiplication :")
print(mul3)


Addition of two matrix :
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Multiplication of two matrix :
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Multiplication of two matrix using (dot ) :
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise multiplication :
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
