<a href="https://colab.research.google.com/github/kashishthorat812-bit/NumPy_Project/blob/main/TASK13_Q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# create a 1D Array with 8 zero using zeros() method
print("1D Array With 8 Zeros :")
a=np.zeros(8)
print(a)

# Create a 2D Array of shape (4,4)
print("\n4*4 Array of ones :")
a1=np.ones([4,4])
print(a1)

# Create a 3*3 matrix of zeros
print("\n3*3 matrix of zeros :")
a2=np.zeros([3,3])
print(a2)

1D Array With 8 Zeros :
[0. 0. 0. 0. 0. 0. 0. 0.]

4*4 Array of ones :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3*3 matrix of zeros :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
