<a href="https://colab.research.google.com/github/kashishthorat812-bit/NumPy_Project/blob/main/TASK13_Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# create a 1D Array
print("1D Array :")
a=np.array([10,20,30,40,50])
print(a)
print("Shape = ",a.shape)
print("Data type = ",a.dtype)

# create a 2D Array
print("\n2D array :")
a1=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a1)
print("Shape = ",a1.shape)
print("Data type = ",a1.dtype)

1D Array :
[10 20 30 40 50]
Shape =  (5,)
Data type =  int64

2D array :
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape =  (3, 3)
Data type =  int64
